sequenceDiagram
    actor User
    
    User->>+GitHub new branch: Create PR
    GitHub new branch->>GitHub Action: Trigger
    GitHub Action->>GitHub Action: npm run test
    GitHub Action->>GitHub Action: Validate JSON
    GitHub Action->>+verifyMainnetShortlist: Execute
    verifyMainnetShortlist-->>GitHub Action: graceful stop
    GitHub Action->>GitHub Action: Check for changes
    GitHub Action->>GitHub new branch:commit changes
    GitHub new branch->>-User: Actions successful
