name: Validate and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install jsonschema

      - name: Validate JSON
        run: |
          jsonschema -i ./json/linea-goerli-token-shortlist.json ./json/schema/l2-token-list-schema.json

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install NPM dependencies
        run: npm ci

      - name: Run NPM tests
        run: npm run test
